apiVersion: v1
kind: BatchJob
metadata:
  name: nav2
  subname: testX
  execClusters: ['kube']
  edgeResourceGroup: ['public'] # default
  useRobotResource: true
  description: 'Combination 1, 2, 3, 4'

jobSpec:
  # maxParallelism: 10
  # maxRetry: 3
  startupTimeout: 120 # secs
  runningTimeout: 420 # secs
  
  varyingParameters:
    # KubeROS generates job set with all possible combinations of following parameters
    - toRosParamMap: nav2-edge-eval-parameters
      paramName: world
      # valueList: ['warehouse', 'maze']
      valueList: ['warehouse', 'maze']

    - toRosParamMap: nav2-edge-eval-parameters
      paramName: localization_method
      valueList: ['slamtoolbox', 'amcl', 'rtabmap']

    - toRosParamMap: nav2-edge-eval-parameters
      paramName: goal_poses
      valueList: ['0.7,0.0,0.0', '1.0,-0.5,0.0']


  lifecycleModule:
    rosModuleName: turtlebot4-sim-all-in-one
    repeatNum: 10

  volume:
    type: 'nfs' # 'localhost' / 'nfs' / 'azure_default' / 'longhorn'
    mountPath: '/ws/rosbags'
    requests: '20Gi'
    name: 'dummy-name'
    nfsServer: 'xxx' # ip or hostname can be resolved by DNS
    nfsRootPath: '/srv/nfs4'
    username: 'ubuntu'
    # hostpath will be generated by kuberos

  resources:
    numProNode: 0
    requests:
      cpu: "3000m"
      memory: "1Gi"
    optimals:
      cpu: "6000m"
      memoery: "1Gi"

  advances:
    groupDataInStorage: false
    saveLogsInVolume: true

rosModules:
  - name: turtlebot4-sim-all-in-one
    image: metagoto/nav2_sim_humble:v1.2.3-cyclone
    entrypoint: ["/entrypoint.sh x2goglx2 ros2 launch nav2_edge_eval nav2_edge_eval.launch.py"]
    # entrypoint: ["sleep 5"]
    sourceWs: /ws/install
    preference: [onboard] 

    requirements: 
      latency: 50ms
      dynamicRescheduling: false
      privilege: true
      peripheral: ['ur-robot'] 
      nvidia: false # placeholder for the future
      containerRuntime: containerd/docker # placeholder for the future

    launchParameters: # Placeholder -> Not used in this example
      record_rosbag: {launch-parameters.record_rosbag}
      world: {launch-parameters.world}
      headless: {launch-parameters.headless}
      goal_poses: {launch-parameters.goal_poses}
      experiment_name: {launch-parameters.experiment_name}
      localization_method: {launch_parameters.localization_method}

    rosParameters: 
      - name: launch-parameters
        type: key-value
        valueFrom: nav2-edge-eval-parameters
      - name: environment-variables
        type: key-value
        valueFrom: ign-env-parameters


rosParamMap:

  - name: nav2-edge-eval-parameters
    type: key-value
    data:
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      record_rosbag: true
      world: warehouse # warehouse / maze / depot
      headless: true
      goal_poses: '0.7,0.0,0.0'
      loop_execution: false
      experiment_name: test_evaluation
      localization_method: rtabmap  # slamtoolbox / amcl / rtabmap

  - name: ign-env-parameters
    type: key-value
    data:
      IGN_PARTITION: 'sim'
      STARTX11: true
      NOVNC_ENABLE: true
      WINDOW_MANAGER_ENABLE: true
      SIZEW: '1920'
      SIZEH: '1080'
