apiVersion: v1
kind: ApplicationDeployment
metadata:
  name: hello-humble-dev-2
  rosVersion: humble
  appVersion: dev-1
  targetFleet: test-fleet
  targetRobots: ['simbot-1']
  edgeResourceGroup: ['public'] # default

rosModules:
  - name: hello-world-talker
    image: <registery>/ros2-basic-examples:v2-param
    entrypoint: ["ros2 launch examples_rclpy_minimal_publisher publisher.launch.py"]

    preference: [onboard] # Preference for scheduler
    
    launchParameters: 
      robot_ip: {SIM_ARM.ROBOT_IP} # hardware specific parameters -> Uppercase
      init_topic: {launch_parameters.init_topic}

    requirements: 
      latency: 50ms
      dynamicRescheduling: false
      privilege: true
      peripheral: ['sim-arm'] 
      
    rosParameters: 
      - name: launch_parameters
        type: key-value
        valueFrom: helloworld-launch-parameters

      - name: minimal_publisher_params
        type: yaml
        valueFrom: publisher-param.yaml
        mountPath: /workspace/config/minimal_publisher
        
    staticFiles: 
      - name: ml_weights_container
        requiredBindType: container 
        hostpath: /workspace/configs/ml_model_weights
        valueFrom: ml-weights-container

rosParamMap:
  - name: helloworld-launch-parameters
    type: key-value
    data:
      init_topic: 'KuberROS'

  - name: publisher-param.yaml
    type: yaml
    path: /workspace/examples/hello_world/config_files/helloword_publisher_params.yml

staticFileMap: 
  - name: ml-weights-container 
    bindType: container
    container: 
      - image: <container image address> 
        pullSecret: <name of your credential in KubeROS database>


